# Generated by Django 5.0.4 on 2024-04-03 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dependencia', models.CharField(max_length=100)),
                ('telefono_dependencia', models.CharField(max_length=20)),
                ('correo_dependencia', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cc_externo', models.CharField(max_length=20)),
                ('nombre_usuario_externo', models.CharField(max_length=100)),
                ('email_usuario_externo', models.EmailField(max_length=254)),
                ('telefono_externo', models.CharField(max_length=20)),
                ('responsable_usuario_externo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_espacio', models.CharField(max_length=100)),
                ('maximo_persona_espacio', models.IntegerField()),
                ('tablero_espacio', models.BooleanField(default=False)),
                ('videobeam_espacio', models.BooleanField(default=False)),
                ('cantidad_sillas_espacio', models.IntegerField()),
                ('conectividad_internet', models.BooleanField(default=False)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_horario', models.DateField()),
                ('hora_inicio_horario', models.TimeField()),
                ('hora_final_horario', models.TimeField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('dia_reserva', models.CharField(max_length=50)),
                ('hora_inicio_reserva', models.TimeField()),
                ('hora_final_reserva', models.TimeField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
                ('usuario_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.usuarioexterno')),
            ],
        ),
    ]
